export const PRIMARY_ROLES = [
  'SOFTWARE_ENGINEER',
  'DATA_SCIENTIST',
  'PRODUCT_MANAGER',
  'DESIGNER',
  'DEVOPS_ENGINEER',
  'MACHINE_LEARNING_ENGINEER',
  'FRONTEND_ENGINEER',
  'BACKEND_ENGINEER',
  'FULL_STACK_ENGINEER',
  'MOBILE_ENGINEER',
  'QA_ENGINEER',
  'SECURITY_ENGINEER',
  'ANALYST',
  'RESEARCHER',
  'OTHER',
];

export const REPORT_REASONS = ['EXPIRED', 'MISLEADING', 'NOT_TIER_ONE'];

export const USER_ROLES = ['JOB_SEEKER', 'RECRUITER'];